### ISSUE TITLE
SQL API isn't proxied

### ISSUE THREAD

**Issue by TrashPandacoot** [DomoApps/ryuu-proxy#21]
[The SQL API](https://developer.domo.com/docs/dev-studio-references/data-api#SQL%20API) isn't being proxied.

maybe it was called "dql" at some point and it was changed to "sql" when the endpoints were made available?

added a new path to check tested it locally. PR #20

**Comment by jpumford** [comment]
You're totally right, the API is so new we haven't used it with `ryuu-proxy` yet. I left a review for you PR.

Thanks!

**Comment by TrashPandacoot** [comment]
Fixed back in April, 2019 when PR #20 was merged
