### ISSUE TITLE
is dqlPattern dead code?

### ISSUE THREAD

**Issue by quantumZebraPDX** [DomoApps/ryuu-proxy#22]
https://github.com/DomoApps/ryuu-proxy/blob/227c78598757301327927de267438abebb6000ac/src/lib/Transport/index.ts#L41

is the dql pattern here dead code? I don't see anything on developer.domo.com that would be proxied by that pattern. Not sure if there's something not released publicly on developer.domo.com or if this can be removed.

**Comment by ttingey** [comment]
Tom, thanks for being thorough on these docs. There are APIs that are not publicly documented because of their complexity of use. We did train on them at Domopalooza this year, but for the most part recommend the new sql endpoints instead, which you already added. Thanks.
