### ISSUE TITLE
cannot install latest version (4.2.0) due to missing peer dependency

### ISSUE THREAD

**Issue by TrashPandacoot** [DomoApps/ryuu-proxy#53]
Hello, not sure if this repo is dead or not. Doesn't appear to have any of the changes for the more recent versions published on npm.

Anyway, when trying to install the latest version, 4.2.0, I get the following error:
```
ryan@Ryans-MacBook-Pro acquisition-and-development-react % npm i -D @domoinc/ryuu-proxy@latest
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @domoinc/ryuu-proxy@4.2.0
npm WARN Found: ryuu@undefined
npm WARN node_modules/ryuu
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer ryuu@"^4.2.0" from @domoinc/ryuu-proxy@4.2.0
npm WARN node_modules/@domoinc/ryuu-proxy
npm WARN   dev @domoinc/ryuu-proxy@"4.2.0" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ryuu@^4.2.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Looks like the version of ryuu it's targeting hasn't been published to npm. [The latest version on npm](https://www.npmjs.com/package/ryuu) I'm seeing is 4.1.4

Did the latest version of this ryuu-proxy get published and publishing the recent version of the peer dependency get forgotten?

**Comment by Caledrith** [comment]
Ryuu 4.2.0 has been delayed heavily by unexpected bugs and feature requests. It's currently in final testing. If you want to try our current beta for it, use `npm i -g ryuu@beta`, but you should also use `ryuu-proxy@beta` for the most features. ryuu-proxy peer dependency with ryuu was included mostly to make sure that your configs are aligned, as there was a breaking change between versions 3 and 4 of ryuu. Let me know if you have any further issues.

**Comment by jasonleehodges** [comment]
This should be resolved by now, so I'm closing this issue. If you are still experiences problems, please re-open.
