### ISSUE TITLE
README.md typo?

### ISSUE THREAD

**Issue by skouzini** [DomoApps/ryuu-proxy#56]
Under [With Express/Connect](https://github.com/DomoApps/ryuu-proxy#with-express--connect), should `const app = express();` be changed to `const app = connect()`? I just ask because that is what the [Connect docs show](https://github.com/senchalabs/connect#create-an-app). 

*As a side note, does that* `app.use(proxy.express())` *line automatically handle requests from* `domo.get()` *and other methods?*

**Comment by Caledrith** [comment]
Express and connect are two different Node middleware packages. `const app = connect()` can be used instead of `const app = express()`, but express is by far (5x) the more popular package and thus should be the default in our documentation.

Correct.

**Comment by jasonleehodges** [comment]
Yeah to be more explicit with your second question:

> As a side note, does that app.use(proxy.express()) line automatically handle requests from domo.get() and other methods?

Ryuu proxy checks every HTTP request being sent from your local dev server, compares it to a regular expression of internal domo endpoints, and if it matches it proxies that request to your domo instance. If it doesn't match the regex, it allows the HTTP request to flow through to the internet as normal.
